version: '3.1'

services:
  db:
    image: mysql
    container_name: summer-camp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      TZ: Europe/Prague
    ports:
      - "3300:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: summer-camp-adminer
    restart: unless-stopped
    ports:
      - "9025:8080"
